[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"
type = "stdio"

[mcp_servers.fetch]
args = ["mcp-server-fetch"]
command = "uvx"
type = "stdio"

[mcp_servers.sequential-thinking]
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]
command = "npx"
type = "stdio"
